### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4

{
  "name": "다쿠아즈",
  "description": "상품 설명",
  "items": [
    {
      "count": 5,
      "name": "딸기맛 다쿠아즈",
      "price": 3500
    }
  ]
}


### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4

{
  "productId": 1,
  "name": "초코맛 다쿠아즈",
  "price": 3500,
  "count": 1
}


### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4

{
  "id" : 1,
  "name": "다쿠아즈",
  "description": "상품 설명",
  "items": [
    {
      "id" : 1,
      "name": "초코맛 다쿠아즈",
      "price": 3000,
      "count": 5
    }
  ]
}


### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4

{
  "id" : 1,
  "name": "초코맛 다쿠아즈",
  "price": 4000,
  "count": 15
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4


### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaSm5xd1g4RkYyMUdCTmZuckZMWHFKTm9ReGh1emFSbWFlVEZ3VTVYN3hNPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjYxMjM1OTI2LCJleHAiOjE2NjEzMjIzMjZ9.P3_WsjNmVz9NFPMKGzEqeVE_gLbneo8En03taAjHGu4


### 상품 검색 조회
GET http://localhost:8082/search/product?name=다쿠아즈


### 상품 상세 조회
GET http://localhost:8082/search/product/detail?productId=1


### 장바구니 상품 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5aG5haWpCZFptQnBtMDQ4T1JNZzh3PT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlcyI6IkNVU1RPTUVSIiwiaWF0IjoxNjYxMjM1OTU0LCJleHAiOjE2NjEzMjIzNTR9.mizlDGWQdM45Ryf2-HNyHlPLnI5-XyYfXRHsas56kGI

{
  "id" : 1,
  "sellerId" : 1,
  "name": "다쿠아즈",
  "description": "상품 설명",
  "items": [
    {
      "id" : 1,
      "count": 1,
      "name": "딸기맛 다쿠아즈",
      "price": 3500
    }
  ]
}